ConfigVersion: '2.0'
Exploits:
  Other:
    PreventCommandsInBed: false
    PreventHoppersToUnloadedChunks: true
    PreventBedrockDestruction: true
    DisableChestsOnMobs: false
    PunishForChestsOnMobs: false
    PreventEndPortalDestruction: true
    DisableRidingExploitableMobs: false
    PreventMinecartsInBoats: false
    PreventBedExplosions: false
    PreventInvalidElytraFlight: false
    PreventNestedShulkers: true
    PreventRailDupe: false
    PreventInvalidPotions: true
    PreventItemSwapLagExploit: true
  BookExploit:
    DisableBookWriting: false
  Teleport:
    PearlPhasing: true
  MineCart:
    RemoveExistingGlitchedMinecarts: false
    MinecartBlockWhiteList: []
    PreventMinecartGlitch: false
    PreventHeadInsideBlocks: false
  PortalDupe:
    NetherWhiteList:
    - Donkey
    - Ghast
    EndWhiteList:
    - elder_guardian
    - guardian
    BlockNonPlayersInEndPortal: false
    NetherWhiteListMode: true
    BlockNonPlayersInNetherPortal: false
    NotifyBlockedPortalAttempts: false
    EndWhiteListMode: true
  OverStack:
    RemoveItemsOfType:
    - Cod_Spawn_Egg
    - Barrier
    - Bedrock
    GroupStack: []
    AllowStack:
    - POTION
    PreventOverStackedItemInHoppers: true
    RemoveOverstackedItems: true
    StackWhiteListMode: true
    FixOverstackedItemInstead: false
  SignExploit:
    DestroyBadSignsOnChunkLoad: false
  1_14_Exploits:
    Traders:
      ZombieVillagerTransformChance: 0
      BlockVillagerTradeCheesing: false
      VillagerRestockTime: 0
    Misc: {}
    Entities: {}
  RNGEnchant:
    PreventRNGEnchant: true
  Nether:
    NetherYLevel: 128
    ExcludeNetherWorldFromHeightCheck: []
    BlockPlayersAboveNether: false
    KillPlayersBelowNether: false
    BlockBuildingAboveNether: true
    EnsureSafeTeleportLocationIfAboveCeiling: true
  DropperDupe:
    BlockLoopedDroppers: true
  Enchants: {}
  Fishing:
    KickForAutoClickerFishing: false
  FishMod:
    WarnPlayerThenKickInsteadOfNotify: false
    MaxFishToNotifyStaffThenBlock: 5
    WatchForAutoFishMod: false
    MaxFishAllowedBeforeKick: 5
  TNTDupe:
    PreventIndirectTNTPowerDupe: false
  3rdParty:
    BlockCMIShulkerStacking: true
  NetherPortal:
    PreventPortalTrap: false
  Looting:
    PreventLootingExploit: false
  EndGateway:
    PreventEndGatewayCrashExploit: true
  1_15_Exploits:
    Dupes:
      PreventTripwireDupe: false
  LavaDupe:
    PreventLavaDupe: false
  1_16_Exploits:
    Dupes: {}
  Minecart:
    AlsoPreventHeadInside:
    - COMPOSTER
  RecordDupe: false
  NegativeDurability: true
Exploit:
  LagMachines:
    End Crystal: true
    ArmorStand: true
  Teleport:
    CorrectionNotify: false
UserRequested:
  Misc:
    NotifyInsteadOfBlock: []
  ItemRemoval:
    ItemLoresToRemove:
    - '"Back'
    BlockEnchantingInstead: false
    ItemNamesToRemove:
    - Cod Spawn Egg
    - Back to VoteGUI
    BlockRepairsInstead: false
    NameLoreStrictMatchMode: false
    RemoveItemsMatchingName: true
  Spawners: {}
  Obscure:
    HackedShulker:
      CheckGroundForBadShulkerAtLogin: false
      DestroyInvalidShulkers: false
    HopperCheck:
      IgnoreAllHopperChecks: false
    IgnoreAllShulkerPlaceChecks: false
    BlockBadItemsFromCreativeTab: false
  Mobs:
    PreventZombieItemPickup: false
  Cobble:
    PreventCobbleGenerators: false
  Obsure:
    Misc:
      RemoveAllRenamedItems: false
Misc:
  BreakMachinesInsteadOfDroppingItems: true
  NotifyNearbyPlayers: true
  DisableInWorlds: []
  InGameOffenseNotifications: true
  LogOffensesInSeparateFile: true
  ItemScanTimer: 10
  Spawners:
    PreventSpawnEggsOnSpawners: true
