ConfigVersion: '2.0'
Exploits:
  PortalDupe:
    NetherWhiteListMode: true
    BlockNonPlayersInEndPortal: true
    BlockNonPlayersInNetherPortal: true
    EndWhiteListMode: false
    EndWhiteList:
    - falling_block
    - item
    NetherWhiteList: []
    NotifyBlockedPortalAttempts: false
  1_14_Exploits:
    Traders:
      ZombieVillagerTransformChance: 65
      BlockVillagerTradeCheesing: false
      VillagerRestockTime: 10
  OverStack:
    StackWhiteListMode: true
    RemoveItemsOfType: []
    AllowStack:
    - POTION
    FixOverstackedItemInstead: false
    GroupStack: []
    RemoveOverstackedItems: true
    PreventOverStackedItemInHoppers: true
  Other:
    PreventEndPortalDestruction: true
    DisableRidingExploitableMobs: true
    PreventBedExplosions: false
    PreventHoppersToUnloadedChunks: true
    PreventNestedShulkers: true
    PreventInvalidPotions: true
    PreventCommandsInBed: false
    PreventInvalidElytraFlight: false
    PreventRailDupe: false
    PunishForChestsOnMobs: false
    PreventMinecartsInBoats: true
    PreventItemSwapLagExploit: true
    PreventBedrockDestruction: true
    DisableChestsOnMobs: true
  LavaDupe:
    PreventLavaDupe: true
  MineCart:
    RemoveExistingGlitchedMinecarts: false
    PreventHeadInsideBlocks: false
    PreventMinecartGlitch: true
    MinecartBlockWhiteList: []
  Minecart:
    AlsoPreventHeadInside:
    - COMPOSTER
  Looting:
    PreventLootingExploit: true
  Nether:
    NetherYLevel: 128
    KillPlayersBelowNether: true
    BlockBuildingAboveNether: false
    ExcludeNetherWorldFromHeightCheck: []
    BlockPlayersAboveNether: false
    EnsureSafeTeleportLocationIfAboveCeiling: false
  BookExploit:
    DisableBookWriting: false
  Fishing:
    KickForAutoClickerFishing: false
  FishMod:
    WatchForAutoFishMod: false
    WarnPlayerThenKickInsteadOfNotify: false
    MaxFishAllowedBeforeKick: 5
    MaxFishToNotifyStaffThenBlock: 5
  1_15_Exploits:
    Dupes:
      PreventTripwireDupe: true
  SignExploit:
    DestroyBadSignsOnChunkLoad: false
  3rdParty:
    BlockCMIShulkerStacking: true
  RecordDupe: true
  NetherPortal:
    PreventPortalTrap: false
  NegativeDurability: true
  RNGEnchant:
    PreventRNGEnchant: true
  EndGateway:
    PreventEndGatewayCrashExploit: true
  Teleport:
    PearlPhasing: false
  TNTDupe:
    PreventIndirectTNTPowerDupe: false
  DropperDupe:
    BlockLoopedDroppers: true
UserRequested:
  ItemRemoval:
    ItemNamesToRemove: []
    BlockEnchantingInstead: false
    ItemLoresToRemove: []
    RemoveItemsMatchingName: false
    NameLoreStrictMatchMode: false
    BlockRepairsInstead: false
  Mobs:
    PreventZombieItemPickup: false
  Obscure:
    BlockBadItemsFromCreativeTab: false
    HackedShulker:
      DestroyInvalidShulkers: false
      CheckGroundForBadShulkerAtLogin: false
    IgnoreAllShulkerPlaceChecks: false
    HopperCheck:
      IgnoreAllHopperChecks: false
  Misc:
    NotifyInsteadOfBlock: []
  Cobble:
    PreventCobbleGenerators: false
  Obsure:
    Misc:
      RemoveAllRenamedItems: false
Exploit:
  LagMachines:
    End Crystal: true
    ArmorStand: true
  Teleport:
    CorrectionNotify: false
Misc:
  ItemScanTimer: 10
  LogOffensesInSeparateFile: true
  DisableInWorlds: []
  NotifyNearbyPlayers: false
  BreakMachinesInsteadOfDroppingItems: true
  InGameOffenseNotifications: true
  Spawners:
    PreventSpawnEggsOnSpawners: true
